version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/study-7
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '4306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: